"""Generate docs/repository-inventory.md: every tracked file, always current.

`docs/repository-manifest.md` answers "what is in the repository, what is
it for, and how done is it". The middle part of that -- *what it is for*
-- is judgement and institutional memory, and stays hand-written. The
first part is a fact about the repository, and a fact restated by hand
goes stale: the manifest spent five days (2026-08-16 to 2026-08-21)
describing `src/` as "docstring-only, no implementation" against 1,470
lines of code, and the test suite as "42 tests, 87% coverage" against
160 at 99%. That is what this file removes the possibility of.

Deliberately a *separate document* from the manifest rather than a
generated section inside it. The precedent is already in the repository:
`docs/index.md` is the generated navigation map and `README.md`'s "Where
to Start" is the curated path, cross-linked rather than merged
(`docs/documentation-guidelines.md`: single primary purpose per doc).
Mixing generated and hand-written content in one file means either the
generator overwrites prose, or a human edits inside a generated file --
both of which the root CLAUDE.md rule exists to prevent.

**What it does not do.** It reports what files exist and which are
empty. It does not assign Draft/Complete status: the manifest's own
legend defines those relative to a Definition of Done that needs a
reader. Emptiness is the one status derivable without judgement, so it
is the only one here. Nor does it report test counts or coverage --
those come from running the suite, not from listing files, and stay
prose with a date attached.

Run via `make inventory`, or `make check-inventory` (part of `make ci`)
to fail if the committed copy is stale. Never hand-edit the output.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "docs" / "repository-inventory.md"

ROOT_GROUP = "(root)"


def tracked_files(root: Path = REPO_ROOT) -> list[str]:
    """Every file git tracks, sorted, as POSIX-style relative paths.

    `git ls-files` rather than a directory walk, deliberately: the
    inventory should describe what the *repository* contains, and a walk
    describes what this disk contains. A walk would pick up `.venv/`,
    tool caches and untracked scratch files, and two clones of the same
    commit could disagree.
    """
    result = subprocess.run(
        ["git", "ls-files"], cwd=root, capture_output=True, text=True, check=True
    )
    return sorted(result.stdout.split())


def group_by_directory(files: list[str]) -> dict[str, list[str]]:
    """`{directory: [paths]}`, both levels sorted.

    Sorted at both levels because the output is byte-compared by
    `--check`; anything depending on filesystem or dictionary ordering
    would fail at random, which is the bug `generate_docs_index.py` hit
    for real on its first Linux run.
    """
    groups: dict[str, list[str]] = {}
    for path in files:
        parent = Path(path).parent.as_posix()
        groups.setdefault(ROOT_GROUP if parent == "." else parent, []).append(path)
    return {directory: sorted(groups[directory]) for directory in sorted(groups)}


def render(files: list[str], root: Path = REPO_ROOT) -> str:
    groups = group_by_directory(files)
    empty_count = sum(1 for path in files if (root / path).stat().st_size == 0)

    lines = [
        "# Repository Inventory",
        "",
        "**Generated by `tools/generators/generate_repository_inventory.py`.",
        "Do not edit by hand** -- run `make inventory`. Per root `CLAUDE.md`,",
        "generated documentation is never edited manually, and",
        "`make check-inventory` fails if this file and the repository disagree.",
        "",
        "This is the complete list of files git tracks: *what* is in the",
        "repository. For *why* each thing exists and how complete it is, read",
        "`repository-manifest.md`, which is hand-written and covers every file",
        "here (enforced by `make check-manifest`).",
        "",
        "Only one status is shown, and only because it needs no judgement: a",
        "file with zero bytes is marked `empty`. Draft-versus-complete is a",
        "reading job and lives in the manifest. Test counts and coverage are",
        "not here either -- those come from running the suite, not from",
        "listing files.",
        "",
        f"**{len(files)} tracked files** across {len(groups)} directories;",
        f"{empty_count} are empty.",
        "",
    ]

    for directory, paths in groups.items():
        lines += [f"## {directory}", ""]
        for path in paths:
            name = Path(path).name
            marker = " -- empty" if (root / path).stat().st_size == 0 else ""
            lines.append(f"- `{name}`{marker}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    content = render(tracked_files())
    check_only = "--check" in sys.argv[1:]

    if check_only:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
        if current == content:
            print("docs/repository-inventory.md is up to date.")
            return 0
        print(
            "docs/repository-inventory.md is stale -- a tracked file was "
            "added, removed, renamed, or emptied without regenerating it.\n"
            "Run 'make inventory' and commit the result."
        )
        return 1

    # newline="\n" for byte-identical output on every platform; see the
    # same note in generate_docs_index.py for what goes wrong without it.
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
