"""Generate docs/planning/dependency-tree.md from the component graph.

Until 2026-08-21 that document was a hand-maintained ASCII tree, and it
disagreed with `docs/architecture/engine.md` about what the engine's
subsystems even are -- different node set, different shape. Both
documents recorded the divergence; two separate backlog items asked
which should be derived from which; nothing resolved it, because
resolving it by editing one of them is just choosing a winner by hand.

`adr/ADR-006-knowledge-graph-scope.md` chose `engine.md`'s nine
conceptual layers, and this script makes that choice structural: the
document is now a view of `planning/data/components.yaml`, whose edges
are in turn quoted from `engine.md`'s own Contract sentences. The two
cannot disagree again without `make check-dependency-tree` failing.

**The engine is a DAG, not a tree**, which is part of why hand-drawing
it kept going wrong: Flux depends on Mesh, Variables, Advection,
Diffusion *and* Boundary Conditions, and an ASCII tree can only show a
node once. The rendered view is therefore dependency *order* -- levels,
where everything in a level depends only on levels above it -- plus each
component's own direct dependencies. That shows the real structure
rather than a tree-shaped approximation of it.

Run via `make dependency-tree` to write the file, or
`make check-dependency-tree` (part of `make ci`) to fail if the
committed copy is stale. Per root CLAUDE.md, the output must never be
edited by hand -- change `planning/data/components.yaml` instead.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "docs" / "planning" / "dependency-tree.md"
COMPONENTS_PATH = Path("planning") / "data" / "components.yaml"


def load_components(root: Path = REPO_ROOT) -> list[dict[str, Any]]:
    with (root / COMPONENTS_PATH).open("r", encoding="utf-8") as handle:
        raw = yaml.safe_load(handle) or {}
    entities: list[dict[str, Any]] = raw.get("entities") or []
    return entities


def _dependencies(component: dict[str, Any]) -> list[str]:
    return sorted(
        str(edge["to"])
        for edge in (component.get("edges") or [])
        if edge.get("type") == "depends_on"
    )


def dependency_levels(components: list[dict[str, Any]]) -> list[list[str]]:
    """Component ids grouped into dependency order.

    Level 0 depends on nothing; level N depends only on levels above it.
    Each level is sorted, so two runs over the same graph produce
    byte-identical output -- without that, `--check` would fail at random
    on dictionary ordering.
    """
    remaining = {str(component["id"]): set(_dependencies(component)) for component in components}
    levels: list[list[str]] = []
    placed: set[str] = set()

    while remaining:
        ready = sorted(name for name, deps in remaining.items() if deps <= placed)
        if not ready:
            # `make check-graph` catches cycles first, and with the actual
            # cycle in the message. Reaching here means this ran without
            # it; fail loudly rather than emit a view silently missing
            # every component caught in the cycle.
            raise ValueError(
                "dependency cycle among: " + ", ".join(sorted(remaining)) + " -- run check-graph"
            )
        levels.append(ready)
        placed.update(ready)
        for name in ready:
            del remaining[name]

    return levels


def render(components: list[dict[str, Any]]) -> str:
    by_id = {str(component["id"]): component for component in components}
    levels = dependency_levels(components)

    lines = [
        "# Dependency Tree",
        "",
        "**Generated by `tools/generators/generate_dependency_tree.py` from",
        f"`{COMPONENTS_PATH.as_posix()}`. Do not edit by hand** -- per root",
        "`CLAUDE.md`, generated documentation is never edited manually, and",
        "`make check-dependency-tree` will fail if this file and the graph",
        "disagree. To change what appears here, change the graph.",
        "",
        "The entities are `docs/architecture/engine.md`'s nine conceptual",
        "layers, and each dependency below is quoted in the graph from that",
        "document's own **Contract** sentence for the layer it points at.",
        "This file was hand-maintained until 2026-08-21 and described a",
        "different set of subsystems than `engine.md` did;",
        "`adr/ADR-006-knowledge-graph-scope.md` resolved that by making one",
        "a view of the other.",
        "",
        "## Dependency order",
        "",
        "The engine is a directed acyclic graph, not a tree -- Flux alone",
        "depends on five other layers, and an ASCII tree can only draw a",
        "node once. So this is dependency *order*: everything in a level",
        "depends only on levels above it, and nothing within its own.",
        "",
        "```text",
    ]

    for index, level in enumerate(levels):
        names = ", ".join(str(by_id[name]["name"]) for name in level)
        lines.append(f"Level {index}: {names}")
    lines += ["```", "", "## Direct dependencies", ""]

    for name in sorted(by_id):
        component = by_id[name]
        dependencies = _dependencies(component)
        if dependencies:
            rendered = ", ".join(f"`{dependency}`" for dependency in dependencies)
            lines.append(f"- **{component['name']}** (`{name}`) depends on {rendered}.")
        else:
            lines.append(f"- **{component['name']}** (`{name}`) depends on nothing.")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render(load_components())
    check_only = "--check" in sys.argv[1:]

    if check_only:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
        if current == content:
            print("docs/planning/dependency-tree.md is up to date.")
            return 0
        print(
            "docs/planning/dependency-tree.md is stale -- the component graph "
            "changed without regenerating it.\n"
            "Run 'make dependency-tree' and commit the result."
        )
        return 1

    # newline="\n" for byte-identical output on every platform; see the
    # same note in generate_docs_index.py for what goes wrong without it.
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
